//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauiWhisper.Translations {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MauiWhisper.Translations.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   App Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Capture Status に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CaptureStatus {
            get {
                return ResourceManager.GetString("CaptureStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encoding Audio to 16000Hz に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConvertingAudio {
            get {
                return ResourceManager.GetString("ConvertingAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownloadButtonLabel {
            get {
                return ResourceManager.GetString("DownloadButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Downloading YouTube Video に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownloadingYoutubeVideo {
            get {
                return ResourceManager.GetString("DownloadingYoutubeVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English Only に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EnglishOnlyLabel {
            get {
                return ResourceManager.GetString("EnglishOnlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not find ffmpeg. In order to run Drastic.Whisper, please install ffmpeg first. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FFMpegMissingError {
            get {
                return ResourceManager.GetString("FFMpegMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Path, URL... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileExamplePlaceholder {
            get {
                return ResourceManager.GetString("FileExamplePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not find file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileMissingError {
            get {
                return ResourceManager.GetString("FileMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generate Subtitles に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateSubtitlesButton {
            get {
                return ResourceManager.GetString("GenerateSubtitlesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generating Subtitles... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GeneratingSubtitles {
            get {
                return ResourceManager.GetString("GeneratingSubtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automatic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LanguageAuto {
            get {
                return ResourceManager.GetString("LanguageAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Listening... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Listening {
            get {
                return ResourceManager.GetString("Listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not find model. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModelMissingError {
            get {
                return ResourceManager.GetString("ModelMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Model に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModelTextLabel {
            get {
                return ResourceManager.GetString("ModelTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multi-Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MultipleLanguagesLabel {
            get {
                return ResourceManager.GetString("MultipleLanguagesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Audio Streams に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoAudioStreams {
            get {
                return ResourceManager.GetString("NoAudioStreams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenFileButton {
            get {
                return ResourceManager.GetString("OpenFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Model に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenModelButton {
            get {
                return ResourceManager.GetString("OpenModelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PathTextLabel {
            get {
                return ResourceManager.GetString("PathTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stalled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Stalled {
            get {
                return ResourceManager.GetString("Stalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not transcode file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TranscodeFiledError {
            get {
                return ResourceManager.GetString("TranscodeFiledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transcribe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TranscribeButtonLabel {
            get {
                return ResourceManager.GetString("TranscribeButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transcribing... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Transcribing {
            get {
                return ResourceManager.GetString("Transcribing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Translate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TranslateButton {
            get {
                return ResourceManager.GetString("TranslateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Whisper Model に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WhisperModelHeader {
            get {
                return ResourceManager.GetString("WhisperModelHeader", resourceCulture);
            }
        }
    }
}
