//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauiWhisper.Translations {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MauiWhisper.Translations.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        internal static string CaptureStatus {
            get {
                return ResourceManager.GetString("CaptureStatus", resourceCulture);
            }
        }
        
        internal static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        internal static string ConvertingAudio {
            get {
                return ResourceManager.GetString("ConvertingAudio", resourceCulture);
            }
        }
        
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        internal static string DownloadButtonLabel {
            get {
                return ResourceManager.GetString("DownloadButtonLabel", resourceCulture);
            }
        }
        
        internal static string DownloadingYoutubeVideo {
            get {
                return ResourceManager.GetString("DownloadingYoutubeVideo", resourceCulture);
            }
        }
        
        internal static string EnglishOnlyLabel {
            get {
                return ResourceManager.GetString("EnglishOnlyLabel", resourceCulture);
            }
        }
        
        internal static string FFMpegMissingError {
            get {
                return ResourceManager.GetString("FFMpegMissingError", resourceCulture);
            }
        }
        
        internal static string FileExamplePlaceholder {
            get {
                return ResourceManager.GetString("FileExamplePlaceholder", resourceCulture);
            }
        }
        
        internal static string FileMissingError {
            get {
                return ResourceManager.GetString("FileMissingError", resourceCulture);
            }
        }
        
        internal static string GenerateSubtitlesButton {
            get {
                return ResourceManager.GetString("GenerateSubtitlesButton", resourceCulture);
            }
        }
        
        internal static string GeneratingSubtitles {
            get {
                return ResourceManager.GetString("GeneratingSubtitles", resourceCulture);
            }
        }
        
        internal static string LanguageAuto {
            get {
                return ResourceManager.GetString("LanguageAuto", resourceCulture);
            }
        }
        
        internal static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        internal static string Listening {
            get {
                return ResourceManager.GetString("Listening", resourceCulture);
            }
        }
        
        internal static string ModelMissingError {
            get {
                return ResourceManager.GetString("ModelMissingError", resourceCulture);
            }
        }
        
        internal static string ModelTextLabel {
            get {
                return ResourceManager.GetString("ModelTextLabel", resourceCulture);
            }
        }
        
        internal static string MultipleLanguagesLabel {
            get {
                return ResourceManager.GetString("MultipleLanguagesLabel", resourceCulture);
            }
        }
        
        internal static string NoAudioStreams {
            get {
                return ResourceManager.GetString("NoAudioStreams", resourceCulture);
            }
        }
        
        internal static string OpenFileButton {
            get {
                return ResourceManager.GetString("OpenFileButton", resourceCulture);
            }
        }
        
        internal static string OpenModelButton {
            get {
                return ResourceManager.GetString("OpenModelButton", resourceCulture);
            }
        }
        
        internal static string PathTextLabel {
            get {
                return ResourceManager.GetString("PathTextLabel", resourceCulture);
            }
        }
        
        internal static string Stalled {
            get {
                return ResourceManager.GetString("Stalled", resourceCulture);
            }
        }
        
        internal static string TranscodeFiledError {
            get {
                return ResourceManager.GetString("TranscodeFiledError", resourceCulture);
            }
        }
        
        internal static string TranscribeButtonLabel {
            get {
                return ResourceManager.GetString("TranscribeButtonLabel", resourceCulture);
            }
        }
        
        internal static string Transcribing {
            get {
                return ResourceManager.GetString("Transcribing", resourceCulture);
            }
        }
        
        internal static string WhisperModelHeader {
            get {
                return ResourceManager.GetString("WhisperModelHeader", resourceCulture);
            }
        }
    }
}
